// 取得元マスターの初期候補(仕様 3・4)。
// URL をコードへ大量にハードコードしないという方針に基づき、この設定は
// 「シード」としてのみ使い、実行時は必ず DB(CrawlerSource テーブル)を参照する。
// 新しい取得元を追加する際は、このファイルへ1エントリ追加 + parsers/ 以下に
// parser を1つ追加するだけで済む plugin 的な構成にしている(仕様 40)。

export type SourceType =
  | "federation"
  | "promotion"
  | "gym_directory"
  | "event_directory"
  | "fighter_directory"
  | "external_database"
  | "api"
  | "gym_official";

export interface SourceSeed {
  id: string;
  name: string;
  baseUrl: string;
  entryUrl: string;
  category: string; // bjj / boxing / mma / kickboxing / judo など(ゆるい分類)
  disciplineId: string | null;
  sourceType: SourceType;
  isOfficial: boolean;
  trustScore: number; // 1-5。公式ソースを優先(仕様11)
  rateLimitMs: number;
  maxConcurrency: number;
  // 実装済み parser の登録名。未実装のものは "unimplemented" とし enabled=false で登録だけしておく。
  parserName: string;
  enabled: boolean;
}

// 信頼度の基本方針(仕様11): 公式ジム/連盟/大会ページ=5, Google Places=4, Tapology等=3, 一般民間DB=2
export const SOURCE_SEEDS: SourceSeed[] = [
  // ---- BJJ / グラップリング ----
  {
    id: "jbjjf-academy",
    name: "JBJJF 加盟アカデミー",
    baseUrl: "https://www.jbjjf.com",
    entryUrl: "https://www.jbjjf.com/academylist_latest/",
    category: "bjj",
    disciplineId: "bjj",
    sourceType: "gym_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "jbjjf",
    enabled: true,
  },
  {
    id: "sjjjf",
    name: "SJJJF",
    baseUrl: "https://sjjjf.org",
    entryUrl: "https://sjjjf.org/",
    category: "bjj",
    disciplineId: "bjj",
    sourceType: "federation",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "ibjjf",
    name: "IBJJF",
    baseUrl: "https://ibjjf.com",
    entryUrl: "https://ibjjf.com/",
    category: "bjj",
    disciplineId: "bjj",
    sourceType: "federation",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "adcc",
    name: "ADCC",
    baseUrl: "https://adcombat.com",
    entryUrl: "https://adcombat.com/adcc-events/",
    category: "grappling",
    disciplineId: "grappling",
    sourceType: "event_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "ajp",
    name: "AJP Tour",
    baseUrl: "https://ajptour.com",
    entryUrl: "https://ajptour.com/en/events-1",
    category: "grappling",
    disciplineId: "grappling",
    sourceType: "event_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  // ---- ボクシング ----
  {
    id: "jbc-gym",
    name: "JBC 全国ジム住所録",
    baseUrl: "https://jbc.or.jp",
    entryUrl: "https://jbc.or.jp/gym/",
    category: "boxing",
    disciplineId: "boxing",
    sourceType: "gym_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "jbc",
    enabled: true,
  },
  {
    id: "jbc-match",
    name: "JBC 試合予定",
    baseUrl: "https://jbc.or.jp",
    entryUrl: "https://jbc.or.jp/match/",
    category: "boxing",
    disciplineId: "boxing",
    sourceType: "event_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "jbc-match",
    enabled: true,
  },
  {
    id: "jbc-register",
    name: "JBC 登録・変更情報",
    baseUrl: "https://jbc.or.jp",
    entryUrl: "https://jbc.or.jp/register/",
    category: "boxing",
    disciplineId: "boxing",
    sourceType: "fighter_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "jbc-register",
    enabled: true,
  },
  {
    id: "jbc-transfer",
    name: "JBC 移籍情報",
    baseUrl: "https://jbc.or.jp",
    entryUrl: "https://jbc.or.jp/transfer/",
    category: "boxing",
    disciplineId: "boxing",
    sourceType: "fighter_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "jbc-transfer",
    enabled: true,
  },
  // ---- MMA ----
  {
    id: "rizin-mma",
    name: "RIZIN MMA選手一覧",
    baseUrl: "https://jp.rizinff.com",
    entryUrl: "https://jp.rizinff.com/fighters/mma",
    category: "mma",
    disciplineId: "mma",
    sourceType: "fighter_directory",
    isOfficial: true,
    trustScore: 5,
    // ヘッドレスブラウザでの取得は重いため、通常サイトより間隔を空ける。
    rateLimitMs: 3000,
    maxConcurrency: 1,
    parserName: "rizin-mma",
    enabled: true,
  },
  {
    id: "rizin-kick",
    name: "RIZIN キックボクシング選手一覧",
    baseUrl: "https://jp.rizinff.com",
    entryUrl: "https://jp.rizinff.com/fighters/kick",
    category: "kickboxing",
    disciplineId: "kickboxing",
    sourceType: "fighter_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 3000,
    maxConcurrency: 1,
    parserName: "rizin-kick",
    enabled: true,
  },
  {
    id: "shooto-fighters",
    name: "修斗 選手紹介",
    baseUrl: "https://www.shooto-mma.com",
    entryUrl: "https://www.shooto-mma.com/fighters/",
    category: "mma",
    disciplineId: "mma",
    sourceType: "fighter_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "shooto",
    enabled: true,
  },
  {
    id: "shooto-schedule",
    name: "修斗 大会スケジュール",
    baseUrl: "https://www.shooto-mma.com",
    entryUrl: "https://www.shooto-mma.com/schedule/",
    category: "mma",
    disciplineId: "mma",
    sourceType: "event_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "pancrase",
    name: "PANCRASE",
    baseUrl: "https://www.pancrase.co.jp",
    entryUrl: "https://www.pancrase.co.jp/",
    category: "mma",
    disciplineId: "mma",
    sourceType: "promotion",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "pancrase-fighters",
    name: "PANCRASE 選手データ",
    baseUrl: "https://www.pancrase.co.jp",
    entryUrl: "https://www.pancrase.co.jp/data/prfl/index.html",
    category: "mma",
    disciplineId: "mma",
    sourceType: "fighter_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "pancrase-schedule",
    name: "PANCRASE 大会",
    baseUrl: "https://www.pancrase.co.jp",
    entryUrl: "https://www.pancrase.co.jp/rls/",
    category: "mma",
    disciplineId: "mma",
    sourceType: "event_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "deep",
    name: "DEEP",
    baseUrl: "https://www.deep2001.com",
    entryUrl: "https://www.deep2001.com/fighters/",
    category: "mma",
    disciplineId: "mma",
    sourceType: "fighter_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "deep",
    enabled: true,
  },
  {
    id: "grachan",
    name: "GRACHAN",
    baseUrl: "https://grachan.jp",
    entryUrl: "https://grachan.jp/",
    category: "mma",
    disciplineId: "mma",
    sourceType: "promotion",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "fighting-nexus",
    name: "Fighting NEXUS",
    baseUrl: "https://fighting-nexus.net",
    entryUrl: "https://fighting-nexus.net/",
    category: "mma",
    disciplineId: "mma",
    sourceType: "promotion",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "gladiator",
    name: "GLADIATOR",
    baseUrl: "https://gladiator-fc.com",
    entryUrl: "https://gladiator-fc.com/",
    category: "mma",
    disciplineId: "mma",
    sourceType: "promotion",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  // ---- キックボクシング / ムエタイ ----
  {
    id: "k1",
    name: "K-1",
    baseUrl: "https://www.k-1.co.jp",
    entryUrl: "https://www.k-1.co.jp/",
    category: "kickboxing",
    disciplineId: "kickboxing",
    sourceType: "promotion",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "k1-gym",
    name: "K-1 公認ジム",
    baseUrl: "https://www.k-1.co.jp",
    entryUrl: "https://www.k-1.co.jp/ama/gym",
    category: "kickboxing",
    disciplineId: "kickboxing",
    sourceType: "gym_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "k1-fighter",
    name: "K-1 選手",
    baseUrl: "https://www.k-1.co.jp",
    entryUrl: "https://www.k-1.co.jp/fighter",
    category: "kickboxing",
    disciplineId: "kickboxing",
    sourceType: "fighter_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "k1-schedule",
    name: "K-1 大会",
    baseUrl: "https://www.k-1.co.jp",
    entryUrl: "https://www.k-1.co.jp/schedule",
    category: "kickboxing",
    disciplineId: "kickboxing",
    sourceType: "event_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "rise",
    name: "RISE 選手紹介",
    baseUrl: "https://rise-rc.com",
    entryUrl: "https://rise-rc.com/fighter",
    category: "kickboxing",
    disciplineId: "kickboxing",
    sourceType: "fighter_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "rise",
    enabled: true,
  },
  {
    id: "knockout",
    name: "KNOCK OUT",
    baseUrl: "https://knockoutkb.com",
    entryUrl: "https://knockoutkb.com/",
    category: "kickboxing",
    disciplineId: "kickboxing",
    sourceType: "promotion",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "njkf",
    name: "NJKF",
    baseUrl: "https://www.njkf.info",
    entryUrl: "https://www.njkf.info/",
    category: "kickboxing",
    disciplineId: "kickboxing",
    sourceType: "promotion",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "shootboxing",
    name: "Shoot Boxing",
    baseUrl: "https://shootboxing.org",
    entryUrl: "https://shootboxing.org/",
    category: "kickboxing",
    disciplineId: "kickboxing",
    sourceType: "promotion",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  // ---- 柔道 ----
  {
    id: "judo-dojo-navi",
    name: "全日本柔道連盟 道場ナビ",
    baseUrl: "https://www.judo.or.jp",
    entryUrl: "https://www.judo.or.jp/dojo-navi/",
    category: "judo",
    disciplineId: "judo",
    sourceType: "gym_directory",
    isOfficial: true,
    trustScore: 5,
    rateLimitMs: 2000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  // ---- 補完DB(民間) ----
  {
    id: "tapology",
    name: "Tapology",
    baseUrl: "https://www.tapology.com",
    entryUrl: "https://www.tapology.com/",
    category: "mma",
    disciplineId: null,
    sourceType: "external_database",
    isOfficial: false,
    trustScore: 3,
    rateLimitMs: 3000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "thegyms",
    name: "THE GYMS",
    baseUrl: "https://thegyms.jp",
    entryUrl: "https://thegyms.jp/",
    category: "mixed",
    disciplineId: null,
    sourceType: "external_database",
    isOfficial: false,
    trustScore: 2,
    rateLimitMs: 3000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
  {
    id: "mma-japan",
    name: "MMA Japan",
    baseUrl: "https://www.mma-japan.net",
    entryUrl: "https://www.mma-japan.net/",
    category: "mma",
    disciplineId: "mma",
    sourceType: "external_database",
    isOfficial: false,
    trustScore: 2,
    rateLimitMs: 3000,
    maxConcurrency: 1,
    parserName: "unimplemented",
    enabled: false,
  },
];

export const DISCIPLINE_SEEDS: { id: string; name: string; category: string }[] = [
  { id: "mma", name: "総合格闘技(MMA)", category: "combat" },
  { id: "bjj", name: "ブラジリアン柔術", category: "grappling" },
  { id: "grappling", name: "グラップリング", category: "grappling" },
  { id: "boxing", name: "ボクシング", category: "striking" },
  { id: "kickboxing", name: "キックボクシング・ムエタイ", category: "striking" },
  { id: "judo", name: "柔道", category: "grappling" },
  { id: "karate", name: "空手", category: "striking" },
  { id: "wrestling", name: "レスリング", category: "grappling" },
  { id: "taekwondo", name: "テコンドー", category: "striking" },
];

// 大会(events)の organizationId 用。source を追加した際、その運営団体がまだここに
// なければ1行追加する(仕様18: organizations)。
export const ORGANIZATION_SEEDS: {
  id: string;
  name: string;
  organizationType: string;
  officialUrl: string;
}[] = [
  { id: "jbc", name: "日本ボクシングコミッション", organizationType: "commission", officialUrl: "https://jbc.or.jp/" },
  { id: "rizin", name: "RIZIN", organizationType: "promotion", officialUrl: "https://jp.rizinff.com/" },
  { id: "shooto", name: "修斗", organizationType: "promotion", officialUrl: "https://www.shooto-mma.com/" },
  { id: "pancrase", name: "PANCRASE", organizationType: "promotion", officialUrl: "https://www.pancrase.co.jp/" },
  { id: "rise", name: "RISE", organizationType: "promotion", officialUrl: "https://rise-rc.com/" },
  { id: "jbjjf", name: "日本ブラジリアン柔術連盟", organizationType: "federation", officialUrl: "https://www.jbjjf.com/" },
];
